[sbs_factcheck]
title = "다음 뉴스 ─ SBS 사실은"
url = "https://news.daum.net/series/252353"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[mbc_factcheck]
title = "다음 뉴스 ─ MBC 알고보니"
url = "https://news.daum.net/series/5165002"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[kbs_factcheck]
title = "다음 뉴스 ─ KBS 팩트체크K"
url = "https://news.daum.net/series/1664634"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[channela_factcheck]
title = "다음 뉴스 ─ 채널A 팩트맨"
url = "https://news.daum.net/series/5157383"
entrySelector = "ul.list_news li"
titleSelector = "a.link_txt"
linkSelector = "a"
contentSelector = "p.desc_thumb"
waitUntil = "networkidle"

[factcheck]
title = "다음 뉴스 ─ 팩트체크"
url = "https://focus.daum.net/ch/news/factcheck"
entrySelector = "ul.list_news.news_type2 li"
titleSelector = "strong.tit_txt"
linkSelector = "a"
contentSelector = "div.desc_thumb"
waitUntil = "networkidle"
onFail = "stale"
